/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia2.interfazgrafica;

import static guia2.interfazgrafica.DeTodoSA.productos;
import java.awt.event.KeyEvent;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class CargaProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargaProductos
     */
    public CargaProductos() {
        initComponents();
        jcbCategoria.addItem("LIMPIEZA");
        jcbCategoria.addItem("PERFUMERIA");
        jcbCategoria.addItem("COMESTIBLES");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxCodigo = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jtxDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxPrecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtxStock = new javax.swing.JTextField();
        jbtNuevo = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Gestión de Productos");

        jLabel2.setText("Código");

        jtxCodigo.setText("0000");
        jtxCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxCodigoFocusGained(evt);
            }
        });
        jtxCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxCodigoKeyTyped(evt);
            }
        });

        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guia2/imagenes/lupa.png"))); // NOI18N
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jtxDescripcion.setText("Descripcion");
        jtxDescripcion.setEnabled(false);
        jtxDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxDescripcionFocusGained(evt);
            }
        });
        jtxDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxDescripcionActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripcion");

        jtxPrecio.setText("0.00");
        jtxPrecio.setEnabled(false);
        jtxPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxPrecioFocusGained(evt);
            }
        });
        jtxPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxPrecioKeyTyped(evt);
            }
        });

        jLabel4.setText("Precio");

        jLabel5.setText("Rubro");

        jcbCategoria.setEnabled(false);

        jLabel6.setText("Stock");

        jtxStock.setText("0.00");
        jtxStock.setEnabled(false);
        jtxStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxStockFocusGained(evt);
            }
        });
        jtxStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxStockKeyTyped(evt);
            }
        });

        jbtNuevo.setText("Nuevo");
        jbtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNuevoActionPerformed(evt);
            }
        });

        jbtGuardar.setText("Guardar");
        jbtGuardar.setEnabled(false);
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtEliminar.setText("Eliminar");
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxDescripcion)
                                        .addComponent(jtxPrecio)
                                        .addComponent(jcbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtxStock))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jbtNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtSalir)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jtxStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNuevo)
                    .addComponent(jbtGuardar)
                    .addComponent(jbtEliminar)
                    .addComponent(jbtSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxDescripcionActionPerformed

    private void jbtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNuevoActionPerformed
       int codigo = buscarCodigo();
       jtxCodigo.setText(codigo + "");
       jtxDescripcion.setText("");
       jtxDescripcion.setEnabled(true);
       jtxPrecio.setText("0.00");
       jtxPrecio.setEnabled(true);
       jtxStock.setText("0.00");
       jtxStock.setEnabled(true);
       jbtNuevo.setEnabled(false);
       jbtEliminar.setEnabled(false);
       jbtBuscar.setEnabled(false);
       jcbCategoria.setEnabled(true);
       jbtGuardar.setEnabled(true);
       jtxDescripcion.requestFocus();
    }//GEN-LAST:event_jbtNuevoActionPerformed

    private void jtxStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxStockKeyTyped
        char caracter = evt.getKeyChar(); // Convierte la tecla precionada en un caracter y luego los compara con los que siquiero que se cargen!!
        if (((caracter < '0' || caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.' || jtxStock.getText().contains("."))){
            evt.consume();
        }
    }//GEN-LAST:event_jtxStockKeyTyped

    private void jtxCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCodigoKeyTyped
        char caracter = evt.getKeyChar(); // Convierte la tecla precionada en un caracter y luego los compara con los que siquiero que se cargen!!
        if (((caracter < '0' || caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxCodigoKeyTyped

    private void jtxPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxPrecioKeyTyped
        char caracter = evt.getKeyChar(); // Convierte la tecla precionada en un caracter y luego los compara con los que siquiero que se cargen!!
        if (((caracter < '0' || caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.' || jtxPrecio.getText().contains("."))){
            evt.consume();
        }
    }//GEN-LAST:event_jtxPrecioKeyTyped

    private void jtxCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxCodigoFocusGained
        jtxCodigo.selectAll();
    }//GEN-LAST:event_jtxCodigoFocusGained

    private void jtxDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxDescripcionFocusGained
        jtxDescripcion.selectAll();
    }//GEN-LAST:event_jtxDescripcionFocusGained

    private void jtxPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxPrecioFocusGained
        jtxPrecio.selectAll();
    }//GEN-LAST:event_jtxPrecioFocusGained

    private void jtxStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxStockFocusGained
        jtxStock.selectAll();
    }//GEN-LAST:event_jtxStockFocusGained

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // Buscar en el TreeSet si existe un un articulo con el codigo existente en jtxCodigo
        accionBotonBuscar();
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        int codigo = Integer.parseInt(jtxCodigo.getText());
        double precio = Double.parseDouble(jtxPrecio.getText());
        double stock = Double.parseDouble(jtxStock.getText());
        System.out.println(jcbCategoria.getSelectedItem());
        Categorias b = Categorias.valueOf(jcbCategoria.getSelectedItem().toString());
        Articulos a = new Articulos(codigo, jtxDescripcion.getText(), precio, stock, b);
        productos.add(a);
        jtxDescripcion.setEnabled(false);
        jtxPrecio.setEnabled(false);
        jtxStock.setEnabled(false);
        jbtNuevo.setEnabled(true);
        jbtEliminar.setEnabled(true);
        jbtBuscar.setEnabled(true);
        jcbCategoria.setEnabled(false);
        jbtGuardar.setEnabled(false);
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
        if (!jtxCodigo.getText().equals("0000") || !jtxCodigo.getText().isEmpty()){
            int vResp = JOptionPane.showConfirmDialog(this, "Seguro de eliminar el Articulo: " + jtxCodigo.getText() + " - " + jtxDescripcion.getText());
            // en vResp se guarda la respuest adel jption que puede ser 0 1 2 en el orden que aparece los botones en el mismo
            if (vResp == 0){
                Articulos b = crearArticulo();
                boolean vr = productos.remove(b);
                if (vr){
                    b = productos.first();
                    jtxCodigo.setText(b.getCodigo() + "");
                    accionBotonBuscar();
                }else{
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el articulo");
                }
            }
        }
    }//GEN-LAST:event_jbtEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtNuevo;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxDescripcion;
    private javax.swing.JTextField jtxPrecio;
    private javax.swing.JTextField jtxStock;
    // End of variables declaration//GEN-END:variables
    
    private int buscarCodigo(){
        int codigo = 1;
        boolean vEcontrado = true;
        while (vEcontrado){
            vEcontrado = false;
            for (Articulos producto : productos) {
                if (producto.getCodigo() == codigo){
                    vEcontrado = true;
                    break;
                }
            }
            if (vEcontrado){
                codigo++;
            }
        }
        return codigo;
    }
    
    private boolean existeCodigo(int codigo){
        boolean vEcontrado = false;
        for (Articulos productos : productos){
            if (productos.getCodigo() == codigo){
                vEcontrado = true;
                break;
            }
        }
        return vEcontrado;
    }
    private Articulos crearArticulo(){
        int codigo = Integer.parseInt(jtxCodigo.getText());
        double precio = Double.parseDouble(jtxPrecio.getText());
        double stock = Double.parseDouble(jtxStock.getText());
        //System.out.println(jcbCategoria.getSelectedItem());
        Categorias b = Categorias.valueOf(jcbCategoria.getSelectedItem().toString());
        Articulos a = new Articulos(codigo, jtxDescripcion.getText(), precio, stock, b);
        return a;
    }
    private void accionBotonBuscar(){
        if (!jtxCodigo.getText().equals("0000") || !jtxCodigo.getText().isEmpty()){
            int vCodigo = Integer.parseInt(jtxCodigo.getText());
            Articulos vBuscado = null;
            for (Articulos producto : productos) {
                if (producto.getCodigo() == vCodigo){
                    vBuscado = producto;
                    break;
                }
            }
            if (vBuscado != null){ // Asignar datos a los elementos
                jtxCodigo.setText(vBuscado.getCodigo() + "");
                jtxDescripcion.setText(vBuscado.getDescripcion());
                jtxPrecio.setText(vBuscado.getPrecio() + "");
                jcbCategoria.setSelectedItem(vBuscado.getRubro().toString());
                jtxStock.setText(vBuscado.getStock() + "");
            }else{
                JOptionPane.showMessageDialog(this, "Ese codigo no existe");
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un codigo valido");
        }
    }

}
