/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia2.interfazgrafica;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dario
 */
public class ListaProductosFalla extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form ListaProductos
     */
    public ListaProductosFalla() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxPrecio = new javax.swing.JTextField();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbArticulos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jtxCategoria = new javax.swing.JTextField();
        jbtCrearCategoria = new javax.swing.JButton();
        jbtCrearArticulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jtxNombre.setText("Nombre del Producto");
        jtxNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxNombreFocusLost(evt);
            }
        });

        jLabel2.setText("Precio");

        jtxPrecio.setText("0.00");
        jtxPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxPrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxPrecioFocusLost(evt);
            }
        });
        jtxPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxPrecioActionPerformed(evt);
            }
        });
        jtxPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxPrecioKeyTyped(evt);
            }
        });

        jcbCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbCategoriaFocusLost(evt);
            }
        });

        jLabel3.setText("Categoria");

        jTbArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTbArticulos.setToolTipText("Lista de Ariculos");
        jScrollPane1.setViewportView(jTbArticulos);

        jLabel4.setText("Categoria");

        jtxCategoria.setText("Nombre del Producto");
        jtxCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxCategoriaFocusGained(evt);
            }
        });
        jtxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCategoriaActionPerformed(evt);
            }
        });

        jbtCrearCategoria.setText("Crear");
        jbtCrearCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtCrearCategoriaFocusLost(evt);
            }
        });
        jbtCrearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCrearCategoriaActionPerformed(evt);
            }
        });

        jbtCrearArticulo.setText("Crear Articulo");
        jbtCrearArticulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtCrearArticuloFocusLost(evt);
            }
        });
        jbtCrearArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCrearArticuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtCrearCategoria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtCrearArticulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCrearCategoria))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCrearArticulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCrearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCrearCategoriaActionPerformed
        // Carga la Categoria.
        if (!this.jtxCategoria.getText().equals("Nombre del Producto") && this.jtxCategoria.getText().length() > 0 ){ // Comprobamos que no este usando el texto por defecto o este vacio
          boolean vExiste = false;
          for (int i = 0; i < jcbCategoria.getItemCount();i++ ){ // Buscamos si existe la palabra dentro de la lista del combobox
              if (jtxCategoria.getText().equalsIgnoreCase(jcbCategoria.getItemAt(i))){
                  vExiste = true;
              }
          }
          if (!vExiste){
              this.jcbCategoria.addItem(this.jtxCategoria.getText()); // Agregamos si es que no se encontro coincidencia
          }else{
              JOptionPane.showMessageDialog(this, "Ya esta en la lista");
          }
        }
        
    }//GEN-LAST:event_jbtCrearCategoriaActionPerformed

    private void jtxCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxCategoriaFocusGained
        // Cuando se obtiene el Foco en el text seleccionar todo el contenido
        jtxCategoria.selectAll();
    }//GEN-LAST:event_jtxCategoriaFocusGained

    private void jtxNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxNombreFocusGained
        if (this.jcbCategoria.getItemCount() > 0){
            jTbArticulos.selectAll();
        }else{
            jtxCategoria.requestFocus(); 
            JOptionPane.showMessageDialog(this, "Primero Carge las Categorias!!!");
        }
        
    }//GEN-LAST:event_jtxNombreFocusGained

    private void jtxPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxPrecioFocusGained
        jtxPrecio.selectAll();
    }//GEN-LAST:event_jtxPrecioFocusGained

    private void jbtCrearArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCrearArticuloActionPerformed
        // TODO add your handling code here:
        modelo.addRow(new Object[]{jtxNombre.getText(),jcbCategoria.getSelectedItem(),jtxPrecio.getText()});
        
    }//GEN-LAST:event_jbtCrearArticuloActionPerformed

    private void jtxPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxPrecioKeyTyped
        /*
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros && (key != 46)) {
            evt.consume();
        }
        if (jtxPrecio.getText().trim().length() == 12) {
            evt.consume();
        }
        */
        char caracter = evt.getKeyChar(); // Convierte la tecla precionada en un caracter y luego los compara con los que siquiero que se cargen!!
        if (((caracter < '0' || caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.' || jtxPrecio.getText().contains("."))){
            evt.consume();
        }

    }//GEN-LAST:event_jtxPrecioKeyTyped

    private void jbtCrearCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtCrearCategoriaFocusLost
        
    }//GEN-LAST:event_jbtCrearCategoriaFocusLost

    private void jcbCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbCategoriaFocusLost
        
    }//GEN-LAST:event_jcbCategoriaFocusLost

    private void jtxNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxNombreFocusLost
        
    }//GEN-LAST:event_jtxNombreFocusLost

    private void jtxPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxPrecioFocusLost
        
    }//GEN-LAST:event_jtxPrecioFocusLost

    private void jbtCrearArticuloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtCrearArticuloFocusLost
        
    }//GEN-LAST:event_jbtCrearArticuloFocusLost

    private void jtxPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxPrecioActionPerformed

    private void jtxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProductosFalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProductosFalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProductosFalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProductosFalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProductosFalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbArticulos;
    private javax.swing.JButton jbtCrearArticulo;
    private javax.swing.JButton jbtCrearCategoria;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JTextField jtxCategoria;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxPrecio;
    // End of variables declaration//GEN-END:variables
    private void armarCabecera(){
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoria");
        modelo.addColumn("Precio");
        this.jTbArticulos.setModel(modelo);
        
    }
    
    private void cargarDatos(Articulos articulo){
        
    }
}
